# Makefile for chat application
CC = gcc
CFLAGS = -g -Wall
LIBS = -lpthread

SRC = src
OBJ = obj

OBJECTS=$(patsubst $(SRC)/%.c, $(OBJ)/%.o, $(wildcard $(SRC)/*.c))

# --- targets
all: chat
chat: $(OBJECTS) 
	mkdir -p bin/
	$(CC) $(CFLAGS) -o bin/chat $(OBJECTS) $(LIBS)

$(OBJ)/%.o: $(SRC)/%.c
	mkdir -p $(OBJ)
	$(CC) $(CFLAGS) $<

# --- remove binary and executable files
clean:
	rm -f bin/* $(OBJECTS)
